VAR_MEMPTR_CHECKSUM EQU FFFFH 
; Launcher for FLAGS  test 01 : SCF
FLAGS_TEST_01_LAUNCH:	LD BC,0EBFH
	LD HL,FLAGS_TEST_01_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 01 : SCF
FLAGS_TEST_01_EXEC:	CCF
	SCF
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 02 : CCF
FLAGS_TEST_02_LAUNCH:	LD BC,3CEDH
	LD HL,FLAGS_TEST_02_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 02 : CCF
FLAGS_TEST_02_EXEC:	SCF
	CCF
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 03 : DAA
FLAGS_TEST_03_LAUNCH:	LD BC,20FDH
	LD HL,FLAGS_TEST_03_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 03 : DAA
FLAGS_TEST_03_EXEC:	DAA
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 04 : CPL
FLAGS_TEST_04_LAUNCH:	LD BC,B0D6H
	LD HL,FLAGS_TEST_04_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 04 : CPL
FLAGS_TEST_04_EXEC:	CPL
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 05 : NEG
FLAGS_TEST_05_LAUNCH:	LD BC,EE36H
	LD HL,FLAGS_TEST_05_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 05 : NEG
FLAGS_TEST_05_EXEC:	NEG
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 06 : AND
FLAGS_TEST_06_LAUNCH:	LD BC,CB8EH
	LD HL,FLAGS_TEST_06_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 06 : AND
FLAGS_TEST_06_EXEC:	LD A,B
	AND C
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 07 : OR
FLAGS_TEST_07_LAUNCH:	LD BC,C57CH
	LD HL,FLAGS_TEST_07_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 07 : OR
FLAGS_TEST_07_EXEC:	LD A,B
	OR C
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 08 : XOR
FLAGS_TEST_08_LAUNCH:	LD BC,26F4H
	LD HL,FLAGS_TEST_08_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 08 : XOR
FLAGS_TEST_08_EXEC:	LD A,B
	XOR C
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 09 : CP
FLAGS_TEST_09_LAUNCH:	LD BC,1676H
	LD HL,FLAGS_TEST_09_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 09 : CP
FLAGS_TEST_09_EXEC:	LD A,B
	CP C
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 11 : ADD8
FLAGS_TEST_11_LAUNCH:	LD BC,9C3CH
	LD HL,FLAGS_TEST_11_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 11 : ADD8
FLAGS_TEST_11_EXEC:	LD A,C
	ADD A,C
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 12 : ADC8
FLAGS_TEST_12_LAUNCH:	LD BC,6E2AH
	LD HL,FLAGS_TEST_12_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 12 : ADC8
FLAGS_TEST_12_EXEC:	LD A,B
	ADC A,C
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 14 : SUB8
FLAGS_TEST_14_LAUNCH:	LD BC,1EF5H
	LD HL,FLAGS_TEST_14_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 14 : SUB8
FLAGS_TEST_14_EXEC:	LD A,B
	SUB C
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 15 : SBC8
FLAGS_TEST_15_LAUNCH:	LD BC,F6DDH
	LD HL,FLAGS_TEST_15_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 15 : SBC8
FLAGS_TEST_15_EXEC:	LD A,B
	SBC A,C
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 10 : INC8
FLAGS_TEST_10_LAUNCH:	LD BC,48CFH
	LD HL,FLAGS_TEST_10_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 10 : INC8
FLAGS_TEST_10_EXEC:	DEC C
	INC C
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 13 : DEC8
FLAGS_TEST_13_LAUNCH:	LD BC,E0D5H
	LD HL,FLAGS_TEST_13_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 13 : DEC8
FLAGS_TEST_13_EXEC:	INC C
	DEC C
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 16 : ADD16
FLAGS_TEST_16_LAUNCH:	LD BC,E268H
	LD HL,FLAGS_TEST_16_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 16 : ADD16
FLAGS_TEST_16_EXEC:	ADD HL,BC
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 17 : ADC16
FLAGS_TEST_17_LAUNCH:	LD BC,715FH
	LD HL,FLAGS_TEST_17_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 17 : ADC16
FLAGS_TEST_17_EXEC:	LD A,C
	ADD A,A
	ADC HL,BC
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 18 : SBC16
FLAGS_TEST_18_LAUNCH:	LD BC,0E1CH
	LD HL,FLAGS_TEST_18_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 18 : SBC16
FLAGS_TEST_18_EXEC:	LD A,C
	ADD A,A
	SBC HL,BC
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 19 : RLA/RRA
FLAGS_TEST_19_LAUNCH:	LD BC,13C1H
	LD HL,FLAGS_TEST_19_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 19 : RLA/RRA
FLAGS_TEST_19_EXEC:	LD A,C
	RLA
	CALL ADD_FLAGS_TO_CHECKSUM
	LD A,C
	RRA
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 20 : RLCA/RRCA
FLAGS_TEST_20_LAUNCH:	LD BC,13C1H
	LD HL,FLAGS_TEST_20_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 20 : RLCA/RRCA
FLAGS_TEST_20_EXEC:	LD A,C
	RLCA
	CALL ADD_FLAGS_TO_CHECKSUM
	LD A,C
	RRCA
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 21 : RLC/RRC
FLAGS_TEST_21_LAUNCH:	LD BC,10ABH
	LD HL,FLAGS_TEST_21_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 21 : RLC/RRC
FLAGS_TEST_21_EXEC:	LD A,C
	RLC A
	CALL ADD_FLAGS_TO_CHECKSUM
	LD A,C
	RRC A
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 22 : RL/RR
FLAGS_TEST_22_LAUNCH:	LD BC,E221H
	LD HL,FLAGS_TEST_22_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 22 : RL/RR
FLAGS_TEST_22_EXEC:	LD A,C
	RL A
	CALL ADD_FLAGS_TO_CHECKSUM
	LD A,C
	RR A
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 23 : SLA/SRA
FLAGS_TEST_23_LAUNCH:	LD BC,DEFAH
	LD HL,FLAGS_TEST_23_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 23 : SLA/SRA
FLAGS_TEST_23_EXEC:	LD A,C
	SLA A
	CALL ADD_FLAGS_TO_CHECKSUM
	LD A,C
	SRA A
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 24 : SLL/SRL
FLAGS_TEST_24_LAUNCH:	LD BC,5FDDH
	LD HL,FLAGS_TEST_24_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 24 : SLL/SRL
FLAGS_TEST_24_EXEC:	LD A,C
	SLL A
	CALL ADD_FLAGS_TO_CHECKSUM
	LD A,C
	SRL A
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 25 : RLD/RRD
FLAGS_TEST_25_LAUNCH:	LD BC,7997H
	LD HL,FLAGS_TEST_25_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 25 : RLD/RRD
FLAGS_TEST_25_EXEC:	LD H,05H
	LD A,L
	INC L
	RLD
	CALL ADD_FLAGS_TO_CHECKSUM
	LD A,L
	INC L
	RRD
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 26 : LD A,I/R
FLAGS_TEST_26_LAUNCH:	LD BC,220CH
	LD HL,FLAGS_TEST_26_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 26 : LD A,I/R
FLAGS_TEST_26_EXEC:	LD A,I
	CALL ADD_FLAGS_TO_CHECKSUM
	LD A,R
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 27 : BIT n,(HL)
FLAGS_TEST_27_LAUNCH:	LD BC,6208H
	LD HL,FLAGS_TEST_27_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 27 : BIT n,(HL)
FLAGS_TEST_27_EXEC:	LD A,R
	LD L,A
	BIT 0,(HL)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 1,(HL)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 2,(HL)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 3,(HL)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 4,(HL)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 5,(HL)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 6,(HL)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 7,(HL)
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 28 : BIT n,(IX+d)
FLAGS_TEST_28_LAUNCH:	LD BC,4AD9H
	LD HL,FLAGS_TEST_28_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 28 : BIT n,(IX+d)
FLAGS_TEST_28_EXEC:	LD A,R
	LD IXl,A
	BIT 0,(IX+0)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 1,(IX+127)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 2,(IX-128)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 3,(IX+64)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 4,(IX-64)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 5,(IX+32)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 6,(IX-32)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 7,(IX-1)
	JP ADD_FLAGS_TO_CHECKSUM
; Launcher for FLAGS  test 29 : BIT n,(IY+d)
FLAGS_TEST_29_LAUNCH:	LD BC,3A82H
	LD HL,FLAGS_TEST_29_EXEC
	JP FLAGS_TEST_COMMON_EXEC
; Code executed for FLAGS  test 29 : BIT n,(IY+d)
FLAGS_TEST_29_EXEC:	LD A,R
	LD IYl,A
	BIT 0,(IY+0)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 1,(IY+127)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 2,(IY-128)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 3,(IY+69)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 4,(IY-69)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 5,(IY+12)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 6,(IY-12)
	CALL ADD_FLAGS_TO_CHECKSUM
	BIT 7,(IY+1)
	JP ADD_FLAGS_TO_CHECKSUM
; Generic execution environment for flags test
FLAGS_TEST_COMMON_EXEC:	DI
	PUSH BC
	LD (REPLACE_CALL1+1),HL ; Replaces instruction CALL 0000H below with CALL (test EXEC address)
	CALL RESET_FLAGS_CHECKSUM
	LD IX,2000H
	LD IY,2000H
	LD HL,0000H
	LD DE,0000H
	LD BC,0000H
	XOR A
	LD R,A
FLAGS_TEST_CMN_EXEC_AF_VAL:	PUSH BC
	POP AF
REPLACE_CALL1:	CALL 0000H
; ==> call to one of the FLAGS_TEST_nn_EXEC routine
	INC C
	JR NZ,FLAGS_TEST_CMN_EXEC_AF_VAL
	INC B
	JR NZ,FLAGS_TEST_CMN_EXEC_AF_VAL
	LD IY,5C3AH
	EI
	LD HL,(VAR_FLAGS_CHECKSUM) ; Flags checksum value in HL
	LD A,20H
	POP BC
	OR A
	SBC HL,BC ; Compare Flags checksum with expected value
	JP NZ,TEST_SCREEN_TEST_FAILED
	JP TEST_SCREEN_TEST_PASSED
; Launcher for FLAGS  test 30 : LDI
FLAGS_TEST_30_LAUNCH:	LD HL,A0EDH
	LD BC,4487H
	JR FLAGS_TEST_REPEAT_EXEC
; Launcher for FLAGS  test 31 : LDD
FLAGS_TEST_31_LAUNCH:	LD HL,A8EDH
	LD BC,7F0EH
	JR FLAGS_TEST_REPEAT_EXEC
; Launcher for FLAGS  test 32 : LDIR
FLAGS_TEST_32_LAUNCH:	LD HL,B0EDH
	LD BC,9ACCH
	JR FLAGS_TEST_REPEAT_EXEC
; Launcher for FLAGS  test 33 : LDDR
FLAGS_TEST_33_LAUNCH:	LD HL,B8EDH
	LD BC,CE51H
	JR FLAGS_TEST_REPEAT_EXEC
; Launcher for FLAGS  test 34 : CPI
FLAGS_TEST_34_LAUNCH:	LD HL,A1EDH
	LD BC,55DBH
	JR FLAGS_TEST_REPEAT_EXEC
; Launcher for FLAGS  test 35 : CPD
FLAGS_TEST_35_LAUNCH:	LD HL,A9EDH
	LD BC,AC82H
	JR FLAGS_TEST_REPEAT_EXEC
; Launcher for FLAGS  test 36 : INI
FLAGS_TEST_36_LAUNCH:	LD HL,A2EDH
	LD BC,F25DH
	JR FLAGS_TEST_REPEAT_EXEC
; Launcher for FLAGS  test 37 : IND
FLAGS_TEST_37_LAUNCH:	LD HL,AAEDH
	LD BC,4A02H
	JR FLAGS_TEST_REPEAT_EXEC
; Launcher for FLAGS  test 38 : OUTI
FLAGS_TEST_38_LAUNCH:	LD HL,A3EDH
	LD BC,8B66H
	JR FLAGS_TEST_REPEAT_EXEC
; Launcher for FLAGS  test 39 : OUTD
FLAGS_TEST_39_LAUNCH:	LD HL,ABEDH
	LD BC,1156H
	JR FLAGS_TEST_REPEAT_EXEC
FLAGS_TEST_REPEAT_EXEC:	PUSH BC
	LD (REPLACE_CALL2),HL ; Replaces instruction LDI below with one of the repeated instructions from the test table
	CALL RESET_FLAGS_CHECKSUM
	LD BC,0000H
FLAGS_TEST_REPEAT_EXEC_EXT_LOOP:	EXX
	LD HL,1800H
	LD DE,1801H
	LD BC,10FEH
FLAGS_TEST_REPEAT_EXEC_INN_LOOP:	EXX
	PUSH BC
	POP AF
	EXX
; ==> executes one of the repeated instructions from the test table
REPLACE_CALL2:	LDI
	CALL ADD_FLAGS_TO_CHECKSUM
	LD A,B
	OR A
	JR NZ,FLAGS_TEST_REPEAT_EXEC_INN_LOOP
	EXX
	INC C
	JR NZ,FLAGS_TEST_REPEAT_EXEC_EXT_LOOP
	LD HL,(VAR_FLAGS_CHECKSUM)
	LD A,20H
	POP BC
	OR A
	SBC HL,BC ; Compare Flags checksum with expected value
	JP NZ,TEST_SCREEN_TEST_FAILED
	JP TEST_SCREEN_TEST_PASSED
; Launcher for FLAGS  test 40 : DD CB (00-FF)  ROM
FLAGS_TEST_40_LAUNCH:	LD IX,01A0H
	LD BC,D9EBH
	JR FLAGS_TEST_DDCB_EXEC
; Launcher for FLAGS  test 41 : DD CB (00-FF)  RAM
FLAGS_TEST_41_LAUNCH:	LD HL,02ABH
	LD DE,C000H
	LD BC,0100H
	LDIR
	LD IX,C000H
	LD BC,90C0H
	JR FLAGS_TEST_DDCB_EXEC
FLAGS_TEST_DDCB_EXEC:	DI
	PUSH BC
	LD IY,0000H
	LD HL,0000H
	LD DE,0000H
	LD BC,0000H
	PUSH HL
	POP AF
FLAGS_TEST_DDCB_EXEC_LOOP:	LD (REPLACE_CALL3+3),A
REPLACE_CALL3:	RLC (IX+0),B ; <= third byte of opcode replaced with all values between 00 and FF by the line above
	PUSH AF
	ADD IY,DE
	ADD IY,BC
	EX DE,HL
	ADD IY,DE
	POP DE
	ADD IY,DE
	LD D,00H
	LD E,(IX+0)
	ADD IY,DE
	INC IX
	LD A,(REPLACE_CALL3+3)
	INC A
	JR NZ,FLAGS_TEST_DDCB_EXEC_LOOP
	PUSH IY
	POP HL
	LD IY,5C3AH
	EI
	LD A,20H
	POP BC
	OR A
	SBC HL,BC ; Compare Flags checksum with expected value
	JP NZ,TEST_SCREEN_TEST_FAILED
	JP TEST_SCREEN_TEST_PASSED
; Launcher for FLAGS  test 42 : FD CB (00-FF)  ROM
FLAGS_TEST_42_LAUNCH:	LD HL,01A0H
	LD BC,D9EBH
	JR FLAGS_TEST_FDCB_EXEC
; Launcher for FLAGS  test 43 : FD CB (00-FF)  RAM
FLAGS_TEST_43_LAUNCH:	LD HL,02ABH
	LD DE,C000H
	LD BC,0100H
	LDIR
	LD HL,C000H
	LD BC,90C0H
	JR FLAGS_TEST_FDCB_EXEC
FLAGS_TEST_FDCB_EXEC:	DI
	PUSH BC
	PUSH HL
	POP IY
	LD IX,0000H
	LD HL,0000H
	LD DE,0000H
	LD BC,0000H
	PUSH HL
	POP AF
FLAGS_TEST_FDCB_EXEC_LOOP:	LD (REPLACE_CALL4+3),A
REPLACE_CALL4:	RLC (IY+0),B ; <= third byte of opcode replaced with all values between 00 and FF by the line above
	PUSH AF
	ADD IX,DE
	ADD IX,BC
	EX DE,HL
	ADD IX,DE
	POP DE
	ADD IX,DE
	LD D,00H
	LD E,(IY+0)
	ADD IX,DE
	INC IY
	LD A,(REPLACE_CALL4+3)
	INC A
	JR NZ,FLAGS_TEST_FDCB_EXEC_LOOP
	PUSH IX
	POP HL
	LD IY,5C3AH
	EI
	LD A,20H
	POP BC
	OR A
	SBC HL,BC ; Compare Flags checksum with expected value
	JP NZ,TEST_SCREEN_TEST_FAILED
	JP TEST_SCREEN_TEST_PASSED
; Launcher for FLAGS  test 46 : CB (00-FF) 5+3 ROM
FLAGS_TEST_46_LAUNCH:	LD A,01H
	LD (VAR_SAVE_A2),A
	LD IX,01A0H
	LD BC,4D19H
	JR FLAGS_TEST_CB_EXEC
; Launcher for FLAGS  test 47 : CB (00-FF) 5+3 RAM
FLAGS_TEST_47_LAUNCH:	LD A,01H
	LD (VAR_SAVE_A2),A
	LD HL,02ABH
	LD DE,C000H
	LD BC,0100H
	LDIR
	LD IX,C000H
	LD BC,1B66H
	JR FLAGS_TEST_CB_EXEC
; Launcher for FLAGS  test 44 : CB (00-FF)     ROM
FLAGS_TEST_44_LAUNCH:	XOR A
	LD (VAR_SAVE_A2),A
	LD IX,01A0H
	LD BC,4731H
	JR FLAGS_TEST_CB_EXEC
; Launcher for FLAGS  test 45 : CB (00-FF)     RAM
FLAGS_TEST_45_LAUNCH:	XOR A
	LD (VAR_SAVE_A2),A
	LD HL,02ABH
	LD DE,C000H
	LD BC,0100H
	LDIR
	LD IX,C000H
	LD BC,15AEH
	JR FLAGS_TEST_CB_EXEC
FLAGS_TEST_CB_EXEC:	DI
	PUSH BC
	LD IY,0000H
	LD HL,0000H
	LD DE,0000H
	LD BC,0000H
	PUSH HL
	POP AF
FLAGS_TEST_CB_EXEC_LOOP:	LD (FLAGS_TEST_CB_EXEC_CASE1+1),A
	LD (REPLACE_CALL5+1),A
	AND 07H
	CP 06H
	JR NZ,FLAGS_TEST_CB_EXEC_CASE1
	PUSH HL
	PUSH IX
	POP HL
REPLACE_CALL5:	RLC B ; <= third byte of opcode replaced with all values between 00 and FF by the line above at 8B17
	LD A,(HL)
	POP HL
	JR FLAGS_TEST_CB_EXEC_CASE2
FLAGS_TEST_CB_EXEC_CASE1:	RLC B ; <= third byte of opcode replaced with all values between 00 and FF by the line above at 8B14
FLAGS_TEST_CB_EXEC_CASE2:	PUSH AF
	ADD IY,DE
	POP DE
	LD A,(VAR_SAVE_A2)
	OR A
	JR NZ,FLAGS_TEST_CB_EXEC_CASE3
	RES 5,E
	RES 3,E
FLAGS_TEST_CB_EXEC_CASE3:	ADD IY,DE
	ADD IY,BC
	EX DE,HL
	ADD IY,DE
	INC IX
	LD A,(FLAGS_TEST_CB_EXEC_CASE1+1)
	INC A
	JR NZ,FLAGS_TEST_CB_EXEC_LOOP
	PUSH IY
	POP HL
	LD IY,5C3AH
	EI
	LD A,20H
	POP BC
	OR A
	SBC HL,BC ; Compare Flags checksum with expected value
	JP NZ,TEST_SCREEN_TEST_FAILED
	JP TEST_SCREEN_TEST_PASSED
VAR_SAVE_A2:DEFB 00H ; Used to save and restore accumulator in FLAGS_TEST_CB_EXEC
RESET_FLAGS_CHECKSUM:	PUSH HL
	LD HL,VAR_MEMPTR_CHECKSUM
	LD (VAR_FLAGS_CHECKSUM),HL
	POP HL
	RET
ADD_FLAGS_TO_CHECKSUM:	PUSH HL
	PUSH DE
	PUSH BC
	PUSH AF
	PUSH AF
	POP BC
	LD A,C
	LD HL,(VAR_FLAGS_CHECKSUM)
	XOR H
	LD B,A
	LD C,L
	RRCA
	RRCA
	RRCA
	RRCA
	LD L,A
	AND 0FH
	LD H,A
	XOR B
	LD B,A
	XOR L
	AND F0H
	LD L,A
	XOR C
	ADD HL,HL
	XOR H
	LD H,A
	LD A,L
	XOR B
	LD L,A
	LD (VAR_FLAGS_CHECKSUM),HL
	POP AF
	POP BC
	POP DE
	POP HL
	RET
VAR_FLAGS_CHECKSUM:	DEFB 00H ; Flags Checksum value
DEFB 00H
TEST_SCREEN_TEST_FAILED: LD A,FFH
JR ENDNOP
TEST_SCREEN_TEST_PASSED: LD A,0
ENDNOP: NOP

; Constant values extracted from ZX spectrum ROM
; used by RLD/RRD flags test
; must be read only
ORG 0500H
DEFB 28H
DEFB CH
DEFB DDH
DEFB 6EH
DEFB 0H
DEFB 7CH
DEFB ADH
DEFB 67H
DEFB 3EH
DEFB 1H
DEFB 37H
DEFB C3H
DEFB 25H
DEFB 5H
DEFB 6CH
DEFB 18H
DEFB F4H
DEFB 79H
DEFB CBH
DEFB 78H
DEFB 10H
DEFB FEH
DEFB 30H
DEFB 4H
DEFB 6H
DEFB 42H
DEFB 10H
DEFB FEH
DEFB D3H
DEFB FEH
DEFB 6H
DEFB 3EH
DEFB 20H
DEFB EFH
DEFB 5H
DEFB AFH
DEFB 3CH
DEFB CBH
DEFB 15H
DEFB C2H
DEFB 14H
DEFB 5H
DEFB 1BH
DEFB DDH
DEFB 23H
DEFB 6H
DEFB 31H
DEFB 3EH
DEFB 7FH
DEFB DBH
DEFB FEH
DEFB 1FH
DEFB D0H
DEFB 7AH
DEFB 3CH
DEFB C2H
DEFB FEH
DEFB 4H
DEFB 6H
DEFB 3BH
DEFB 10H
DEFB FEH
DEFB C9H
DEFB F5H
DEFB 3AH
DEFB 48H
DEFB 5CH
DEFB E6H
DEFB 38H
DEFB FH
DEFB FH
DEFB FH
DEFB D3H
DEFB FEH
DEFB 3EH
DEFB 7FH
DEFB DBH
DEFB FEH
DEFB 1FH
DEFB FBH
DEFB 38H
DEFB 2H
DEFB CFH
DEFB CH
DEFB F1H
DEFB C9H
DEFB 14H
DEFB 8H
DEFB 15H
DEFB F3H
DEFB 3EH
DEFB FH
DEFB D3H
DEFB FEH
DEFB 21H
DEFB 3FH
DEFB 5H
DEFB E5H
DEFB DBH
DEFB FEH
DEFB 1FH
DEFB E6H
DEFB 20H
DEFB F6H
DEFB 2H
DEFB 4FH
DEFB BFH
DEFB C0H
DEFB CDH
DEFB E7H
DEFB 5H
DEFB 30H
DEFB FAH
DEFB 21H
DEFB 15H
DEFB 4H
DEFB 10H
DEFB FEH
DEFB 2BH
DEFB 7CH
DEFB B5H
DEFB 20H
DEFB F9H
DEFB CDH
DEFB E3H
DEFB 5H
DEFB 30H
DEFB EBH
DEFB 6H
DEFB 9CH
DEFB CDH
DEFB E3H
DEFB 5H
DEFB 30H
DEFB E4H
DEFB 3EH
DEFB C6H
DEFB B8H
DEFB 30H
DEFB E0H
DEFB 24H
DEFB 20H
DEFB F1H
DEFB 6H
DEFB C9H
DEFB CDH
DEFB E7H
DEFB 5H
DEFB 30H
DEFB D5H
DEFB 78H
DEFB FEH
DEFB D4H
DEFB 30H
DEFB F4H
DEFB CDH
DEFB E7H
DEFB 5H
DEFB D0H
DEFB 79H
DEFB EEH
DEFB 3H
DEFB 4FH
DEFB 26H
DEFB 0H
DEFB 6H
DEFB B0H
DEFB 18H
DEFB 1FH
DEFB 8H
DEFB 20H
DEFB 7H
DEFB 30H
DEFB FH
DEFB DDH
DEFB 75H
DEFB 0H
DEFB 18H
DEFB FH
DEFB CBH
DEFB 11H
DEFB ADH
DEFB C0H
DEFB 79H
DEFB 1FH
DEFB 4FH
DEFB 13H
DEFB 18H
DEFB 7H
DEFB DDH
DEFB 7EH
DEFB 0H
DEFB ADH
DEFB C0H
DEFB DDH
DEFB 23H
DEFB 1BH
DEFB 8H
DEFB 6H
DEFB B2H
DEFB 2EH
DEFB 1H
DEFB CDH
DEFB E3H
DEFB 5H
DEFB D0H
DEFB 3EH
DEFB CBH
DEFB B8H
DEFB CBH
DEFB 15H
DEFB 6H
DEFB B0H
DEFB D2H
DEFB CAH
DEFB 5H
DEFB 7CH
DEFB ADH
DEFB 67H
DEFB 7AH
DEFB B3H
DEFB 20H
DEFB CAH
DEFB 7CH
DEFB FEH
DEFB 1H
DEFB C9H
DEFB CDH
DEFB E7H
DEFB 5H
DEFB D0H
DEFB 3EH
DEFB 16H
DEFB 3DH
DEFB 20H
DEFB FDH
DEFB A7H
DEFB 4H
DEFB C8H
DEFB 3EH
DEFB 7FH
DEFB DBH
DEFB FEH
DEFB 1FH
DEFB D0H
DEFB A9H
DEFB E6H
DEFB 20H
DEFB 28H
DEFB F3H
DEFB 79H
DEFB 2FH
DEFB 4FH
DEFB E6H
DEFB 7H
DEFB F6H